### ISSUE TITLE
axis range options can't be auto on one side, and specified on the other

### ISSUE THREAD

**Issue by Dieterbe** [NatelEnergy/grafana-plotly-panel#1]
Hello,
first of all thanks for this plugin. it looks promising.  I'm trying to make use of it internally at GrafanaLabs for our own monitoring.
One thing I'ld like to do, is specify the lower value of the axes at 0, but leave the max value of the axis on auto. It seems I must specify an upper limit for it to take the lower limit into account as well.

cheers!
Dieter

**Comment by ryantxu** [comment]
interesting.  Looks like plotly does not support this.  But it does have a 'rangemode':
https://plot.ly/javascript/reference/#layout-xaxis-rangemode

I just added that and it will be released in v0.0.3
