### ISSUE TITLE
Axix limits from Template Variable

### ISSUE THREAD

**Issue by JCN-9000** [NatelEnergy/grafana-plotly-panel#13]
Hi
I'm trying to make a 4 quadrant report ( Similar to this : https://i1.wp.com/www.criticaltosuccess.com/wp-content/uploads/2015/02/IMG_Four_Quadrant_Matrix_Static.png ).
Since there is not a way to have the axis displayed on a non zero value I am trying to align 4 panels, but I need to be able to use the axis range ( Display - X Axis - Range = Between ) assigning the Min and Max Values from a Template Variable of grafana. 
Is the panel config able to accept Variables ?
Thanks

**Comment by ryantxu** [comment]
currently no variables in the config.  This seems like a good idea, any help would be great too 😄

**Comment by ryantxu** [comment]
some support with #13, open a new issue if it needs improvement
