### ISSUE TITLE
Can't add Panel

### ISSUE THREAD

**Issue by GiovanniPaoloGibilisco** [NatelEnergy/grafana-plotly-panel#16]
Hi, 
I installed the plugin via CLI on a Grafana v4.5.2 (commit: ec2b0fe) (running on Docker), restarted the container but can't add the pnel to a dashboard. 
I see the plugin in the installed list but when creating a new dhasboard I can't see the new panel type.

**Comment by ryantxu** [comment]
Do you see anything in the chrome developer console?  perhaps an error?  

Are you saying it does not show up in the list of options to add to a new dashboard?  'panel search filter'

**Comment by GiovanniPaoloGibilisco** [comment]
Apparently restarting the container was not enough. with a full docker-compose stop and docker compuse-up the panel shows up.
