### ISSUE TITLE
How to plot x-y or polar  scatter graph with Kairosdb?

### ISSUE THREAD

**Issue by bjjqqkk** [NatelEnergy/grafana-plotly-panel#18]
Hi all,

Thank you, the grafana and plot.ly plugin team, for providing the module  for scatter plot.  I am in a project that requires to plot x-y or polar  scatter plot using the data from Kairosdb.   I have not been able to  figure out how and hope to find help here.  Along the road, I am  actually hoping to find a module or find help in developing such a  module which is able to plot wind rose diagrams.

My Kairosdb has a couple of metrics and tag-pairs.  Each tag-pairs  represents a time series of data.   The example is as follows:

The metric name is "CR1000", having tag-paris like "xreadings, x1",  "xreadings, x2", "xreadings, x3", ...., "yreadings, y1", "yreadings,  y2", .... and so on.   I am trying to do scatter plots using "xreadings,  x1" as x and "yreadings, y1" as y.    Is this possible?   Our plot.ly  plugin is version 0.0.3.

My current experience was that: In our plot.ly control panel, there were  initially only two tag fields for data.  I tried to fill "xreadings" in  the first tag field,  "x1" in the second, and click the mouse left botton.   Grafana did not plot anything receiving the event.  Then I  needed to click 'Add (+)' to generate a new form for another pair of tag fields.  We subsequently input "yreadings" and "y1" in the two new tag fields and click the left mouse botton, grafana generates a plot using "yreadings, y1" for both x and y values (ie. data points are on x=y line).  Was there something missing in my operation?

Any help is welcome and thank you in advance!

For more information, our example JSON data read:

"name": "CR1000",
         "tags": {
             "xreadings": "x1"
         },
         "datapoints": [
             [1359788400000, 12.3],
             [1359788300000, 13.2],
             [1359788410000, 23.1]
         ]

and

"name": "CR1000",
         "tags": {
             "yreadings": "y1"
         },
         "datapoints": [
             [1359788400000, 45.6],
             [1359788300000, 56.4],
             [1359788410000, 65.4]
         ]

**Comment by ryantxu** [comment]
Sorry, I don't have any experience with Kairosdb
