### ISSUE TITLE
Static curves

### ISSUE THREAD

**Issue by jonasdig** [NatelEnergy/grafana-plotly-panel#19]
Hi, 
I would like to have the possibility to add static curves in the plot. My goal is to show a static pump curve and add points on top off that based on measured values. This will tell me if the pump is performing as expected or if there is something wrong. Is that something that will be possible in future releases? I fully understand if my request has limited use for anyone else and is not prioritized.

Pump curve: https://www.myodesie.com/images/wiki/2/centrifugalpump.jpg

**Comment by samhatchett** [comment]
while this does seem like a special use case, I also have this need. my plan so far is to just plot a synthetically-generated "ideal" data set along with the telemetered data.

**Comment by ryantxu** [comment]
Yes, with #9, the goal is to show multiple series.

**Comment by jonasdig** [comment]
That would be grate.

**Comment by ryantxu** [comment]
With #9/#30, i think this is supported.

However, you will need the additional data to come from a query
