### ISSUE TITLE
Not-matching time stamps

### ISSUE THREAD

**Issue by gavol** [NatelEnergy/grafana-plotly-panel#23]
Hello,

thanks a lot for your great plug-in.

May I ask what happens when two series do not have exactly the same time stamps? Does the plug-in tries to make some interpolation? Or points with not-matching time stamps are just not shown?

Thanks in advance for your answer.

**Comment by ryantxu** [comment]
It currently gives an error saying they need to match.  patches are welcome to support other cases 😄
