### ISSUE TITLE
Panel contents dont resize accordingly

### ISSUE THREAD

**Issue by Strum355** [NatelEnergy/grafana-plotly-panel#27]
Examples: 
- Works:
![image](https://user-images.githubusercontent.com/18282288/42391498-8046176a-8147-11e8-8bbe-8d430510d706.png)
- Doesnt work:
![image](https://user-images.githubusercontent.com/18282288/42391513-8e0aeeca-8147-11e8-8214-1a58772522d8.png)

Installed according to the installation instructions via grafana-cli. Running Grafana 5.2.1

**Comment by ryantxu** [comment]
Can you explain more what is happening?

Is the scale ok on the first load?  then you refresh and the scale does not change?  are you resizing the browser?

**Comment by Strum355** [comment]
The scale is okay when first loaded. When i go to edit it and exit out of edit mode, the scale no longer works (assuming non-full length panel). It is fixed by resizing the browser so it seems as if it only goes wrong when the panel itself is resized or if the panel isnt full size and you enter and exit editing mode

**Comment by ryantxu** [comment]
I am unable to reproduce this in the master branch... so it may be fixed.  Can you test with 0.0.5-dev?

**Comment by ryantxu** [comment]
![resize](https://user-images.githubusercontent.com/705951/44159738-34a66680-a06d-11e8-9d15-cfa12856bbc3.gif)

It seems ok to me...  reopen if you are still seeing this with latest versions installed
