### ISSUE TITLE
Ramp bound to a time series

### ISSUE THREAD

**Issue by dstreppa** [NatelEnergy/grafana-plotly-panel#3]
Hi,
it should be useful to bind the ramp to a time series (now - as default - it is possible for the time). For example X is the irradiance, Y the power of a PV module and the ramp color is defined by the module's temperature.

**Comment by lzgrablic01** [comment]
I just made a pull request for this: https://github.com/NatelEnergy/grafana-plotly-panel/pull/4

**Comment by ryantxu** [comment]
Thanks @lzgrablic01
