### ISSUE TITLE
Axis labeling issues since #30

### ISSUE THREAD

**Issue by ryantxu** [NatelEnergy/grafana-plotly-panel#31]
Since adding #30, I notice two issues:

1.  Empty X/Y titles should keep the axis unlabled:
![image](https://user-images.githubusercontent.com/705951/44127452-2f4848aa-9ff2-11e8-9d77-7796466989fc.png)

2. The scatter3d plot does not use the configured titles:
![image](https://user-images.githubusercontent.com/705951/44127493-624778ac-9ff2-11e8-9826-2cb082761fa9.png)

@jonyrock -- can you take a look?

**Comment by jonyrock** [comment]
@ryantxu I will take a look in 24 hours

**Comment by jonyrock** [comment]
@ryantxu working on this

**Comment by jonyrock** [comment]
- [ ] Empty X/Y titles should keep the axis unlabled
- [ ] The scatter3d plot does not use the configured titles:

**Comment by ryantxu** [comment]
@jonyrock X/Y fixed, but 3d still different

**Comment by ryantxu** [comment]
fixed in #32
