### ISSUE TITLE
direct image link to plot timing out

### ISSUE THREAD

**Issue by moniCoder** [NatelEnergy/grafana-plotly-panel#55]
The plotly graph is unable to be shared via the Direct link rendered image. I am using another grafana plugin which uses this functionality to create a pdf of the page. Can this be fixed?

**Comment by rheddi02** [comment]
hello sorry to bother you but I have the same issue now as yours. Did you manage to make it? or do you an alternative fo this? TIA

**Comment by ryantxu** [comment]
fixed by #88
