### ISSUE TITLE
Request: Support square axes

### ISSUE THREAD

**Issue by randvoorhies** [NatelEnergy/grafana-plotly-panel#58]
I'm trying to plot 2D positions, and so it would be very helpful to be able to constrain the aspect ratio of the x/y axes to be 1:1 (square).  I'm new to plotly, but it looks like the library does support this (e.g. https://plot.ly/javascript/axes/#fixedratio-axes)

![image](https://user-images.githubusercontent.com/1069819/50322473-df9ab700-0489-11e9-945d-4db29a8a967b.png)

**Comment by ryantxu** [comment]
Just added this:
![image](https://user-images.githubusercontent.com/705951/52491880-f5208900-2b7c-11e9-9fa7-5ac1d1be7564.png)

it will be included in the next release
