### ISSUE TITLE
color based on metric

### ISSUE THREAD

**Issue by wols** [NatelEnergy/grafana-plotly-panel#6]
Great plugin, thanks!
My data source is Elasticsearch and the relevant doc fields are X: delay and Y: clock_offset. The color is to be based on source_address (IP). The screenshot shows left the "green" an right the "yellow" IP spots.

Feature request: Color based on "group by" or "third" metric possible?

![ntpstats-live_scatter-0 0 2](https://cloud.githubusercontent.com/assets/764167/24503030/9815cb56-1550-11e7-8a22-e211a7315bb0.png)

![ntpstats-live_scatter-metrics-0 0 2](https://cloud.githubusercontent.com/assets/764167/24503035/a4305618-1550-11e7-94a2-505c9f28972c.png)

**Comment by ryantxu** [comment]
this is now in master, and will be released in r0.0.3
