### ISSUE TITLE
Download Size reduction

### ISSUE THREAD

**Issue by KrishnaPG** [NatelEnergy/grafana-plotly-panel#60]
This is great plugin. However, when using on dashboard it is taking very very long time to load. When investigated, it looks like it is downloading 2.7MB js file (please refer the below screenshot). The total page size (including data) is 2.8 MB, out of which 2.7MB is just this js file.

The file in question is: 

> /natel-plotly-panel/lib/plotly.min.js?_cache=1548169124278

Is it possible to reduce the size of this? It looks like it is the Plotly standard js file, in which case, would strongly recommend using CDN link, instead of forcing the download from the grafana plugin folder (hosted by users, and mostly does not take advantage of CDN)

![image](https://user-images.githubusercontent.com/4610831/51543436-91f7dc80-1e83-11e9-9219-5ae8a1ac93c2.png)

This slow loading is looking very very awkward for about 20+ seconds on our servers, while all the rest of the panels have loaded and data populated. In the below screenshot the panels in the red areas marked takes lot of time to load because of this heavy file size.

![image](https://user-images.githubusercontent.com/4610831/51543700-2bbf8980-1e84-11e9-8cd5-6879eb88885f.png)

**Comment by ryantxu** [comment]
In master, try:
![image](https://user-images.githubusercontent.com/705951/52386640-c64ec980-2a3b-11e9-99fe-35250b4ec1c7.png)
