### ISSUE TITLE
More gradient color scales

### ISSUE THREAD

**Issue by hoerup** [NatelEnergy/grafana-plotly-panel#63]
I like the Greens and Greys scales - but could you add more gradient color scales lige eg. Blues and Reds ?

**Comment by ryantxu** [comment]
It has the plotly bluered scale:
![image](https://user-images.githubusercontent.com/705951/52361422-15244100-29f3-11e9-885a-9775a438897b.png)

I just added all the scales:`Greys,YlGnBu,Greens,YlOrRd,Bluered,RdBu,Reds,Blues,Picnic,Rainbow,Portland,Jet,Hot,Blackbody,Earth,Electric,Viridis,Cividis.`
