### ISSUE TITLE
scale is displayed when color_option is solid

### ISSUE THREAD

**Issue by ctberthiaume** [NatelEnergy/grafana-plotly-panel#8]
The color ramp scale is displayed when the marker `color_option` is set to `solid` if `showscale` is true. It can be disabled by switching to `ramp` temporarily to expose the `showscale` option, disabling the `showscale` option, then switching back to `solid`. I think this may actually be a bug in plotly.js with how the showscale marker option is handled. https://plot.ly/javascript/reference/#scatter-marker-showscale. The documentation claims that this 'Has an effect only if `marker.color` is set to a numerical array.' But looking at the TRACE debugging console output in the panel I can see that even when the `marker.color` option set to a single color and not an array the color scale may still be displayed if `showscale` is true.

**Comment by ryantxu** [comment]
fixed in 0.0.5
