### ISSUE TITLE
Set custom axes scale

### ISSUE THREAD

**Issue by davidecalza** [NatelEnergy/grafana-plotly-panel#85]
It would be useful to define a fixed scale for x and y axes of the panel for comparison purposes.
Sometimes you need to compare two different panels using the same scale, but at the moment, it scales up automatically without any option to set a custom scale.

**Comment by patricktokeeffe** [comment]
?

I just installed 0.0.6 and it has `Range: Between` as an option for both X and Y axes.

**Comment by davidecalza** [comment]
> ?
> 
> I just installed 0.0.6 and it has `Range: Between` as an option for both X and Y axes.

I updated the plugin and it worked. I guess I had an old version.
